routes/web.php
            Route::get('view-insert', 'DepartmentController@view_insert')->name('department.view_insert');
            Route::match(['get', 'post'], 'process-insert', 'DepartmentController@process_insert')->name('department.process_insert');

            Route::get('view-update/{id}', 'DepartmentController@view_update')->name('department.view_update');
            Route::post('process-update/{id}', 'DepartmentController@process_update')->name('department.process_update');
            Route::get('delete/{id}', 'DepartmentController@delete')->name('department.delete');

            Route::match(['get', 'post'], 'del', 'DepartmentController@del')->name('department.del');
        });

        Route::group(['prefix' => 'course'], function () {
            Route::get('/', 'CourseController@view_all')->name('course.view_all');
            Route::get('view-insert', 'CourseController@view_insert')->name('course.view_insert');
            Route::match(['get', 'post'], 'process-insert', 'CourseController@process_insert')->name('course.process_insert');

            Route::get('view-update/{id}', 'CourseController@view_update')->name('course.view_update');
            Route::post('process-update/{id}', 'CourseController@process_update')->name('course.process_update');
            Route::get('delete/{id}', 'CourseController@delete')->name('course.delete');
            Route::match(['get', 'post'], 'del', 'CourseController@del')->name('course.del');
        });

        Route::group(['prefix' => 'classes'], function () {
            Route::get('/', 'ClassesController@view_all')->name('classes.view_all');
            Route::get('view-insert', 'ClassesController@view_insert')->name('classes.view_insert');
            Route::match(['get', 'post'], 'process-insert', 'ClassesController@process_insert')->name('classes.process_insert');

            Route::get('view-update/{id}', 'ClassesController@view_update')->name('classes.view_update');
            Route::post('process-update/{id}', 'ClassesController@process_update')->name('classes.process_update');
            Route::get('delete/{id}', 'ClassesController@delete')->name('classes.delete');
            Route::match(['get', 'post'], 'del', 'ClassesController@del')->name('classes.del');
        });

        Route::group(['prefix' => 'subject'], function () {
            Route::get('/', 'SubjectController@view_all')->name('subject.view_all');
            Route::get('view-insert', 'SubjectController@view_insert')->name('subject.view_insert');
            Route::match(['get', 'post'], 'process-insert', 'SubjectController@process_insert')->name('subject.process_insert');

            Route::get('view-update/{id}', 'SubjectController@view_update')->name('subject.view_update');
            Route::post('process-update/{id}', 'SubjectController@process_update')->name('subject.process_update');
            Route::get('delete/{id}', 'SubjectController@delete')->name('subject.delete');
            Route::match(['get', 'post'], 'del', 'SubjectController@del')->name('subject.del');
        });

        Route::group(['prefix' => 'profile'], function () {
            Route::get('/', 'profileController@index')->name('profile.my_profile');
            Route::post('changeProfile', 'profileController@changeProfile');
            Route::post('changePassword', 'profileController@changePassword');
        });

        Route::group(['prefix' => 'student'], function () {
            Route::get('/', 'StudentController@view_all')->name('student.view_all');
            Route::get('view-insert', 'StudentController@view_insert')->name('student.view_insert');
            Route::match(['get', 'post'], 'process-insert', 'StudentController@process_insert')->name('student.process_insert');

            Route::get('view-update/{id}', 'StudentController@view_update')->name('student.view_update');
            Route::post('process_update/{id}', 'StudentController@process_update')->name('student.process_update');
            Route::get('delete/{id}', 'StudentController@delete')->name('student.delete');

            Route::get('show', 'StudentController@show')->name('student.show');

            Route::get('add-students', 'StudentController@view_add_students');
            Route::match(['get', 'post'], 'process-add-students', 'StudentController@process_add_students')
                ->name('student.process-add-students');

            Route::get('view_import_excel', 'StudentController@view_import_excel')->name('student.view_import_excel');
            Route::post('process_import_excel', 'StudentController@process_import_excel')->name('student.process_import_excel');
            route::get('excel-student-by-class','StudentController@get_excel_student_by_class')->name('student.get_excel_student_by_class');
            route::get('excel-student-by-department','StudentController@get_excel_student_by_department')->name('student.get_excel_student_by_department');
            Route::get('view_import_excel_year_begin', 'StudentController@view_import_excel_year_begin')->name('student.view_import_excel_year_begin');
            Route::post('process_import_excel_year_begin', 'StudentController@process_import_excel_year_begin')->name('student.process_import_excel_year_begin');

            Route::match(['get', 'post'], 'del', 'StudentController@del')->name('student.del');
        });

        Route::group(['prefix' => 'teacher'], function () {
            Route::view('dashboard', 'teacher.index')->name('teacher.dashboard');

            Route::get('/', 'TeacherController@view_all')->name('teacher.view_all');
            Route::get('view-insert', 'TeacherController@view_insert')->name('teacher.view_insert');
            Route::match(['get', 'post'], 'process_insert', 'TeacherController@process_insert')->name('teacher.process_insert');

            Route::get('view-update/{id}', 'TeacherController@view_update')->name('teacher.view_update');
            Route::post('process-update/{id}', 'TeacherController@process_update')->name('teacher.process_update');
            Route::get('delete/{id}', 'TeacherController@delete')->name('teacher.delete');

            Route::get('show', 'TeacherController@show')->name('teacher.show');

            Route::match(['get', 'post'], 'del', 'TeacherController@del')->name('teacher.del');

            route::get('lock-teacher-account/{id}','TeacherController@lock_teacher_account')->name('teacher.lock_teacher_account');
            route::get('open-teacher-account/{id}','TeacherController@open_teacher_account')->name('teacher.open_teacher_account');
        });


        Route::group(['prefix' => 'assignment'], function () {
            Route::get('view-insert', 'AssignmentController@view_insert')->name('assignment.view_insert');
            Route::match(['get', 'post'], 'process-insert', 'AssignmentController@process_insert')->name('assignment.process_insert');
            Route::get('get-subject', 'AssignmentController@get_subject')->name('assignment.get_subject');
            Route::get('get-class', 'AssignmentController@get_class')->name('assignment.get_classes');
            Route::get('', 'AssignmentController@view_all')->name('assignment.view_all');
            Route::get('get-assignment', 'AssignmentController@get_assignment')->name('assignment.get_assignment');

            Route::get('view-update/{id}', 'AssignmentController@view_update')->name('assignment.view_update');
            Route::match(['get', 'post'], 'process-update/{id}', 'AssignmentController@process_update')->name('assignment.process_update');
        });

        Route::group(['prefix' => 'point'], function () {
            Route::get('view-insert', 'PointController@view_insert')->name('point.view_insert');
            Route::post('process-insert', 'PointController@process_insert')->name('point.process_insert');
            Route::get('get-student', 'PointController@get_student')->name('point.get_student');
            Route::get('get-class', 'PointController@get_class')->name('point.get_classes');

            Route::get('get-classs', 'PointController@get_classs')->name('point.get_classess');

            Route::post('update', 'PointController@update')->name('point.update');

            Route::get('view-update', 'PointController@view_update')->name('point.view_update');
        });

        Route::group(['prefix' => 'rollcall'], function () {
            route::get('/','RollcallController@view_history')->name('rollcall.view_history');

            route::get('get-subject-by-class','RollcallController@get_subject_by_class')
            ->name('rollcall.get_subject_by_class');

            route::get('get-student-attendance-history','RollcallController@get_student_attendance_history')
            ->name('rollcall.get_student_attendance_history');
        });

    });
});


// Teacher
Route::group(['prefix' => 'teacher'], function () {
    Route::group(['middleware' => ['CheckTeacherSession']], function () {
        Route::get('login', 'TeacherController@getLogin')->name('teacher.getLogin');
        Route::post('login', 'TeacherController@postLogin')->name('teacher.postLogin');

        route::view('forgot-password','teacher.forgot_password')->name('teacher.forgot_password');

        route::post('send-email-forgot-password','ForgotPassword@send_email_forgot_password_teacher')
        ->name('teacher.send_email_forgot_password_teacher');

        route::post('check-exist-email-teacher','ForgotPassword@check_exist_email_teacher')
        ->name('teacher.check_exist_email_teacher');

        route::get('change_password/{token}','ForgotPassword@change_password_teacher')
        ->name('teacher.change_password');

        route::post('process-change-password/{token}','ForgotPassword@process_change_password_teacher')
        ->name('teacher.process_change_password');
    });
    Route::get('logout', 'TeacherController@getLogout')->name('teacher.getLogout');

    Route::group(['middleware' => 'CheckTeacherLogin'], function () {

app/Models/Classes.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Classes extends Model
{
    protected $table = 'classes';

    protected $fillable = [
        'classes_name',
        'department_id',
        'course_id'
    ];

    public $timestamps = false;

    public function course()
    {
        return $this->belongsTo('App\Models\Course', 'course_id');
    }

    public function department()
    {
        return $this->belongsTo('App\Models\Department', 'department_id');
    }

    public function array_student()
    {
        return $this->hasMany('App\Models\Student', 'classes_id', 'id');
    }

    public function getFullNameClassAttribute()
    {
        return $this->department->prefix.$this->classes_name.'K'.$this->course->course_name;
    }
}

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $table = 'student';

    protected $fillable = [
        'student_name',
        'email',
        'password',
        'birthday',
        'phone',
        'address',
        'gender',
        'classes_id'
    ];

    public $timestamps = false;

    public function classes()
    {
        return $this->belongsTo('App\Models\Classes', 'classes_id');
    }

    public function points()
    {
        return $this->belongsToMany('App\Models\Subject', 'point', 'student_id','subject_id')->using('App\Models\Point');
    }

    public function getGenderNameAttribute()
    {
        if ($this->gender == 1) {
            return 'Nam';
        } else {
            return "Nữ";
        }
    }
    public function getClassFullNameAttribute()
    {
        return $this->classes->department->prefix . $this->classes->classes_name . 'K' . $this->classes->course->course_name;
    }

    public function studentInfo()
    {
        return $this->selectRaw(" student.id as id,
            student_name,
            if(student.gender=1,'Nam','Nữ') as gender,
            concat(department.prefix,classes.classes_name,'K',course.course_name) as class_name,
            address,birthday,phone,email")
            ->join('classes', 'classes.id', '=', 'student.classes_id')
            ->join('department', 'department.id', '=', 'classes.department_id')
            ->join('course', 'course.id', '=', 'classes.course_id')
            ->get();
    }
}

resources/views/student/index.blade.php
@extends('layouts.theme_ui_student.master')
@section('title', 'Sinh - Viên')
@section('ui-student')
<div id="wrapper">
    @include('layouts.theme_ui_student.navbar')
    <section id="home" class="video-section js-height-full">
        <div class="overlay"></div>
        <div class="home-text-wrapper relative container">
            <div class="home-message">
                <p>Management System</p>
                <small>The website provides full information about students and will always update test scores as soon as possible. If you have any questions, please send feedback by mail.</small>
            </div>
        </div>
        <div class="slider-bottom">
            <span>Explore <i class="fa fa-angle-down"></i></span>
        </div>
    </section>

    <section class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-4 hidden-sm hidden-xs">
                    <div class="custom-module">
                        <img src="{{ asset('public/img/cover/bia-1.png') }}" alt="" class="img-responsive wow slideInLeft">
                    </div><!-- end module -->
                </div><!-- end col -->
                <div class="col-md-8">
                    <div class="custom-module p40l">
                        <h2>We are a passionate <mark>learning system</mark> from<br>
                        Vietnam.</h2>

                        <p>The 3-year training school system includes the following subjects:</p>

                        <hr class="invis">

                        <div class="row">
                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 first">
                                <ul class="check">
                                    <li>HTML - CSS - JS</li>
                                    <li>Bootstrap</li>
                                    <li>Sever Side</li>
                                    <li>PHP</li>
                                    <li>Laravel</li>
                                </ul><!-- end check -->
                            </div><!-- end col-lg-4 -->
                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                <ul class="check">
                                    <li>JAVA</li>
                                    <li>C++</li>
                                    <li>C#</li>
                                    <li>XML</li>
                                    <li>Algorithms</li>
                                </ul><!-- end check -->    
                            </div><!-- end col-lg-4 -->
                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 last">
                                <ul class="check">
                                    <li>Image Processing</li>
                                    <li>Technical English</li>
                                </ul><!-- end check -->
                            </div><!-- end col-lg-4 --> 
                        </div><!-- end row -->   

                        <hr class="invis">

                        <div class="btn-wrapper">
                            <a href="#" class="btn btn-primary">Learn More About us</a>
                        </div>

                    </div><!-- end module -->
                </div><!-- end col -->
            </div><!-- end row -->
        </div><!-- end container -->
    </section>

    <section class="section gb" style="background: #ffffff; padding-top: unset;"></section>

    <section class="section db p120">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="tagline-message text-center">
                        <h3>Howdy, we are AKKHOR, we have brought great experiences through each subject.</h3>
                    </div>
                </div><!-- end col -->
            </div><!-- end row -->
        </div><!-- end container -->
    </section><!-- end section -->

    <section class="section gb nopadtop">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <div class="box m30">
                        <i class="flaticon-computer-tool-for-education"></i>
                        <h4>Learning system</h4>
                        <p>All sections required for online training are included to Edulogy.</p>
                        <a href="#" class="readmore">Read more</a>
                    </div>
                </div><!-- end col -->

                <div class="col-md-6">
                    <div class="box m30">
                        <i class="flaticon-monitor-tablet-and-smartohone"></i>
                        <h4>Works all mobile devices</h4>
                        <p>The most important feature of this template is that it is compatible with all mobile devices. Your customers can also visit your site easily from tablets and phones.</p>
                        <a href="#" class="readmore">Read more</a>
                    </div>
                </div><!-- end col -->

                <div class="col-md-3">
                    <div class="box m30">
                        <i class="flaticon-download-business-statistics-symbol-of-a-graphic"></i>
                        <h4>User Dashboard</h4>
                        <p>We designed the design of all the sub-pages needed for the users.</p>
                        <a href="https://dribbble.com/tags/user_dashboard" class="readmore">Read more</a>
                    </div>
                </div><!-- end col -->
            </div><!-- end row -->

            <hr class="invis">

            <div class="row">
                <div class="col-md-6">
                    <div class="box">
                        <i class="flaticon-html5"></i> <i class="flaticon-css-3"></i>
                        <h4>Compatible HTML5 & CSS3</h4>
                        <p>HTML5 is a markup language used for structuring and presenting content on the World Wide Web. It is the fifth and current version of the HTML standard.</p>
                        <a href="https://www.w3schools.com/html/default.asp" class="readmore">Read more</a>
                    </div>
                </div><!-- end col -->

                <div class="col-md-6">
                    <div class="box">
                        <i class="flaticon-html-coding"></i>
                        <h4>Bootstrap Framework</h4>
                        <p>Bootstrap is a technique of loading a program into a computer by means of a few initial instructions which enable the introduction of the rest of the program from an input device.</p>
                        <a href="https://www.w3schools.com/bootstrap4/default.asp" class="readmore">Read more</a>
                    </div>
                </div><!-- end col -->
            </div><!-- end row -->
        </div><!-- end container -->
    </section>

    <section class="section db">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-4">
                    <div class="stat-count">
                        <h4 class="stat-timer">1230</h4>
                        <h3><i class="flaticon-black-graduation-cap-tool-of-university-student-for-head"></i> Happy Students</h3>
                        <p>Quisque porttitor eros quis leo pulvinar, at hendrerit sapien iaculis. </p>
                    </div><!-- stat-count -->
                </div><!-- end col -->

                <div class="col-lg-4 col-md-4">
                    <div class="stat-count">
                        <h4 class="stat-timer">331</h4>
                        <h3><i class="flaticon-online-course"></i> Course Done</h3>
                        <p>Quisque porttitor eros quis leo pulvinar, at hendrerit sapien iaculis. </p>
                    </div><!-- stat-count -->
                </div><!-- end col -->

                <div class="col-lg-4 col-md-4">
                    <div class="stat-count">
                        <h4 class="stat-timer">8901</h4>
                        <h3><i class="flaticon-coffee-cup"></i> Ordered Coffe's</h3>
                        <p>Quisque porttitor eros quis leo pulvinar, at hendrerit sapien iaculis. </p>
                    </div><!-- stat-count -->
                </div><!-- end col -->
            </div><!-- end row -->
        </div><!-- end container -->
    </section>

    <section class="section">
        <div class="container">
            <div class="section-title text-center">
                <h3>Testimonials</h3>
                <p>Maecenas sit amet tristique turpis. Quisque porttitor eros quis leo pulvinar, at hendrerit sapien iaculis. Donec consectetur accumsan arcu, sit amet fringilla ex ultricies.</p>
            </div><!-- end title -->

            <div class="row">
                <div class="col-md-4">
                    <div class="box testimonial">
                        <p class="testiname"><strong><img src="" alt="" class="img-circle"> Jenny LUXURY</strong></p>
                        <p>Quisque porttitor eros quis leo pulvinar, at hendrerit sapien iaculis. Donec consectetur accumsan arcu, sit amet fringilla ex ultricies.</p>
                        <div class="rating">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                        </div>
                    </div><!-- end testimonial -->
                </div><!-- end col -->

                <div class="col-md-4">
                    <div class="box testimonial">
                        <p class="testiname"><strong><img src="" alt="" class="img-circle"> Martin LEO</strong></p>
                        <p>Quisque porttitor eros quis leo pulvinar, at hendrerit sapien iaculis. Donec consectetur accumsan arcu, sit amet fringilla ex ultricies.</p>
                        <div class="rating">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star-o"></i>
                        </div>
                    </div><!-- end testimonial -->
                </div><!-- end col -->

                <div class="col-md-4">
                    <div class="box testimonial">
                        <p class="testiname"><strong><img src="" alt="" class="img-circle"> John DOE</strong></p>
                        <p>Quisque porttitor eros quis leo pulvinar, at hendrerit sapien iaculis. Donec consectetur accumsan arcu, sit amet fringilla ex ultricies.</p>
                        <div class="rating">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                        </div>
                    </div><!-- end testimonial -->
                </div><!-- end col -->
            </div><!-- end row -->
        </div><!-- end container -->
    </section>

    <section class="section gb" style="background: #ffff; padding:unset;"></section>

    <section class="section bgcolor1" style="background: #ffff; padding-top: unset;"></section>

    @include('layouts.theme_ui_student.footer')
</div><!-- end wrapper -->
@endsection

resources/views/student/insert_students.blade.php
@extends('layouts.master')
@section('master')
<link rel="stylesheet" href="{{asset('public/css/insert_students.css')}}">
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<div id="wrapper" class="wrapper bg-ash">
    <!-- Header Menu Area Start Here -->
    @include('layouts.navbar')
    <!-- Header Menu Area End Here -->
    <!-- Page Area Start Here -->
    <div class="dashboard-page-one">
        <!-- Sidebar Area Start Here -->
        @include('layouts.sidebar')
        <!-- Sidebar Area End Here -->
        <div class="dashboard-content-one">
            <div class="table-responsive">
                <form method="POST" action="{{ route('student.process-add-students') }}" enctype="multipart/form-data">
                    <table id="table" class="table display data-table text-nowrap">
                        @csrf
                        <input type="hidden" value="" v-model="student_number" name="student_number">
                        <thead>
                            <tr>
                                <th>
                                    <div class="form-check">
                                        <input type="checkbox" class="form-check-input checkAll">
                                        <label class="form-check-label">Lớp</label>
                                    </div>
                                </th>
                                <th>Họ và tên</th>
                                <th>Ảnh</th>
                                <th>Email</th>
                                <th>Số điện thoại</th>
                                <th>Giới tính</th>
                                <th>Ngày sinh</th>
                                <th>Địa chỉ</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr v-for="(item,index ) in items" :key="index">
                                <td>
                                    <div class="form-check">
                                        <input type="checkbox" class="form-check-input">
                                        <label class="form-check-label"><select name="classes_id[]">
                                                @foreach ($classes as $class)
                                                <option value="{{ $class->id }}">
                                                    {{ $class->full_name_class }}
                                                </option>
                                                @endforeach
                                            </select></label>
                                    </div>
                                </td>
                                <td><input type="text" name="student_name[]"></td>
                                <td><input :id="index" name="images[]" type="file" @change="onFileChange(index,$event)">
                                    <label :for="index"><img style="width: 31px;height: 31px;" :src='item.src'
                                            alt=""></label>
                                </td>
                                <td><input type="email" name="email[]"></td>
                                <td><input type="text" name="phone[]"></td>
                                <td><select name="gender[]">
                                        <option value="1">Nam</option>
                                        <option value="0">Nữ</option>
                                    </select></td>
                                <td><input type="date" name="birthday[]"></td>
                                <td><input type="text" name="address[]"></td>
                                <td>
                                    <div class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                                            aria-expanded="false">
                                            <span class="flaticon-more-button-of-three-dots"></span>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right">
                                            <a class="dropdown-item" href="#"><i
                                                    class="fas fa-times text-orange-red"></i>Close</a>
                                            <a class="dropdown-item" href="#"><i
                                                    class="fas fa-redo-alt text-orange-peel"></i>Refresh</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                        <button type="submit" class="btn btn-primary  btn-lg">submit</button>
                    </table>
                </form>
            </div>
            @include('layouts.footer')
        </div>
    </div>
    <!-- Page Area End Here -->
</div>
<script>
    const vm = new Vue({
    el: '#table',
    data: {
        url: null,
        items:[
            {
                ten:'',
                src:''
            },
        ],
        student_number:''
    },
    methods: {
        //index là lấy index của thằng input file nhưng vì chỉ số  index của input file trùng với index của img lên dùng luôn
        onFileChange(index,files) {
            const file = files.target.files[0];
            this.items[index].src = URL.createObjectURL(file);
            files.currentTarget.style.display="none";
        },
        add_students(number){
            this.items=[{ten:'',src:''}];
            for(var i=0;i<number-1;i++)
            {
                let obj={ten:'',src:''};
                this.items.push(obj);
            }
        }
    }
});

    (async () => {
        const { value: sv } = await Swal.fire({
        title: 'Nhập số sinh viên muốn thêm',
        input: 'number',
        showCancelButton: true,
        inputValidator: (value) => {
            if (!value) {
            return 'Bạn cần phải nhập số sinh viên'
            }
            else
            {
                vm.add_students(value);
                vm.student_number=value;
            }
        }
    })
    })()
</script>
@endsection